SELECT JOB_ID,COUNT(*) FROM hr_db.employees GROUP BY JOB_ID;

SELECT JOB_ID,MIN(SALARY) FROM hr_db.employees WHERE JOB_ID LIKE "%MAN" GROUP BY JOB_ID;

SELECT DEPARTMENT_ID,SUM(SALARY) FROM hr_db.employees GROUP BY DEPARTMENT_ID;

SELECT JOB_ID,AVG(SALARY) FROM hr_db.employees WHERE JOB_ID != "IT_PROG"GROUP BY JOB_ID;

SELECT JOB_ID,MAX(SALARY) AS max_salary FROM hr_db.employees GROUP BY JOB_ID HAVING max_salary >= 4000;

SELECT DEPARTMENT_ID, AVG(SALARY) FROM hr_db.employees GROUP BY DEPARTMENT_ID HAVING COUNT(*) >10;