SELECT FIRST_NAME,LAST_NAME,SALARY FROM hr_db.employees WHERE (SALARY NOT BETWEEN 10000 AND 15000) AND DEPARTMENT_ID IN (30,100);

SELECT FIRST_NAME,LAST_NAME,HIRE_DATE FROM hr_db.employees WHERE YEAR(HIRE_DATE) = 1987;

SELECT FIRST_NAME FROM hr_db.employees WHERE FIRST_NAME LIKE "%b%" AND FIRST_NAME LIKE "%c%";

SELECT LAST_NAME, JOB_ID, SALARY FROM hr_db.employees WHERE JOB_ID IN ("SH_CLERK","IT_PROG") AND SALARY NOT IN (4500,10000,15000);

SELECT * FROM hr_db.employees WHERE LAST_NAME IN ("BLAKE","SCOTT","KING","FORD");