SELECT FIRST_NAME, LAST_NAME, SALARY FROM hr_db.employees WHERE SALARY > (SELECT SALARY FROM hr_db.employees WHERE LAST_NAME="Bull");

SELECT FIRST_NAME, LAST_NAME FROM hr_db.employees WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM hr_db.departments WHERE DEPARTMENT_NAME LIKE 'IT%');

SELECT FIRST_NAME, LAST_NAME FROM hr_db.employees WHERE JOB_ID IN (SELECT JOB_ID FROM hr_db.jobs WHERE JOB_TITLE LIKE "%Manager%");

SELECT FIRST_NAME, LAST_NAME, SALARY FROM hr_db.employees WHERE SALARY > (SELECT AVG(SALARY) FROM hr_db.employees);

SELECT a.FIRST_NAME, a.LAST_NAME, a.SALARY 
FROM hr_db.employees AS a, (SELECT JOB_ID, MIN(SALARY) AS mini FROM hr_db.employees GROUP BY JOB_ID) AS b 
WHERE a.JOB_ID = b.JOB_ID AND a.salary = b.mini

SELECT a.FIRST_NAME, a.LAST_NAME, a.SALARY 
FROM hr_db.employees AS a, (SELECT DEPARTMENT_ID, MIN(SALARY) AS mini FROM hr_db.employees GROUP BY DEPARTMENT_ID) AS b 
WHERE a.DEPARTMENT_ID = b.DEPARTMENT_ID AND a.salary = b.mini;

SELECT employees.EMPLOYEE_ID,
 employees.FIRST_NAME, 
 employees.LAST_NAME, 
 departments.DEPARTMENT_Name 
FROM hr_db.employees, (SELECT DEPARTMENT_ID, DEPARTMENT_Name FROM hr_db.departments) AS departments 
WHERE employees.DEPARTMENT_ID = departments.DEPARTMENT_ID;

SELECT * FROM (SELECT * FROM hr_db.employees ORDER BY EMPLOYEE_ID DESC LIMIT 10) AS a ORDER BY EMPLOYEE_ID;